In [1]:
import pandas as pd
from analyzer import * 
import seaborn as sns 

sns.set_theme(
    style="whitegrid",
    context="paper",
)

/home/work/.anaconda/envs/privacyovod_new_copy/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
ss = SpubenchResults()  # pd.read_csv('/home/work/yuna/HPA/evaluation/analysis/old/sputbench.csv') 
df = ss.results 
df, pv = ss.finetuning_effect(df)
df['dataset'] = 'Spubench' 
df

['Qwen3-VL-4B-Instruct_A1_JS_vqa_n15_blind_inst']

                    model    finetuned   pid  bias  delta   dataset
0       InternVL 3.5 (8B)  JS VQA (GT)     0  Sha.    0.0  Spubench
1       InternVL 3.5 (8B)  JS VQA (GT)     0    BG    0.0  Spubench
2       InternVL 3.5 (8B)  JS VQA (GT)     1    BG    0.0  Spubench
3       InternVL 3.5 (8B)  JS VQA (GT)     1    CO    0.0  Spubench
4       InternVL 3.5 (8B)  JS VQA (GT)     2    BG    0.0  Spubench
...                   ...          ...   ...   ...    ...       ...
76915  LLaVA‑Mistral (7B)      SFT-VQA  2397    TN    0.0  Spubench
76916  LLaVA‑Mistral (7B)      SFT-VQA  2398    BG    0.0  Spubench
76917  LLaVA‑Mistral (7B)      SFT-VQA  2398    PA    0.0  Spubench
76918  LLaVA‑Mistral (7B)      SFT-VQA  2399    BG    0.0  Spubench
76919  LLaVA‑Mistral (7B)      SFT-VQA  2399    TN    0.0  Spubench

[76920 rows x 6 columns]

In [ ]:
mm = MMStarResults() 
mm.test_model.groupby(['model', 'finetuned']).count()

/tmp/ipykernel_1569965/2556097107.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.human['correct'] = self.human['correct'] * 100

In [ ]:

dfdf, pt = mm.finetuning_effect(mm.test_model) 
dfdf['dataset'] = 'MMStar'  
dfdf.pivot_table(index=['model', 'finetuned'], columns=['dataset', 'category'], values=['delta'], aggfunc='count')

In [ ]:
df.pivot_table(index=['model', 'finetuned'], columns=['dataset', 'category'], values=['delta'], aggfunc='count')

                                                       delta  \
dataset                                               MMStar
category                                   coarse perception
model              finetuned
InternVL 3.5 (8B)  JS VQA (GT)                       33124.0
                   JS-Blind MMStar (n=15)            33124.0
                   JS-Blind VQA (n=10)               33124.0
                   JS-Blind VQA (n=15)               33124.0
                   SFT-Blind MMStar (n=15)           33124.0
                   SFT-Blind VQA                     33124.0
                   SFT-VQA                           33124.0
LLaVA‑Mistral (7B) JS VQA (GT)                       33124.0
                   JS-Blind MMStar (n=15)            33124.0
                   JS-Blind VQA (n=10)               33124.0
                   JS-Blind VQA (n=15)               33124.0
                   SFT-Blind MMStar                  33124.0
                   SFT-Blind VQA                     33124.0
                   SFT-VQA                           33124.0
Qwen3‑VL (4B)      JS VQA (GT)                       33124.0
                   JS-Blind MMStar (n=15)            33124.0
                   JS-Blind VQA (n=10)               33124.0
                   JS-Blind VQA (n=15)               33124.0
                   SFT-Blind VQA                     33124.0
                   SFT-VQA                           33124.0
Qwen3‑VL (8B)      JS VQA (GT)                       33124.0
                   JS-Blind MMStar (n=15)            33124.0
                   JS-Blind VQA (n=10)               33124.0
                   JS-Blind VQA (n=15)               33124.0
                   SFT-Blind MMStar                  33124.0
                   SFT-Blind VQA                     33124.0

                                                                    \
dataset
category                                   fine-grained perception
model              finetuned
InternVL 3.5 (8B)  JS VQA (GT)                             22201.0
                   JS-Blind MMStar (n=15)                  22201.0
                   JS-Blind VQA (n=10)                     22201.0
                   JS-Blind VQA (n=15)                     22201.0
                   SFT-Blind MMStar (n=15)                 22201.0
                   SFT-Blind VQA                           22201.0
                   SFT-VQA                                 22201.0
LLaVA‑Mistral (7B) JS VQA (GT)                             22201.0
                   JS-Blind MMStar (n=15)                  22201.0
                   JS-Blind VQA (n=10)                     22201.0
                   JS-Blind VQA (n=15)                     22201.0
                   SFT-Blind MMStar                        22201.0
                   SFT-Blind VQA                           22201.0
                   SFT-VQA                                 22201.0
Qwen3‑VL (4B)      JS VQA (GT)                             22201.0
                   JS-Blind MMStar (n=15)                  22201.0
                   JS-Blind VQA (n=10)                     22201.0
                   JS-Blind VQA (n=15)                     22201.0
                   SFT-Blind VQA                           22201.0
                   SFT-VQA                                 22201.0
Qwen3‑VL (8B)      JS VQA (GT)                             22201.0
                   JS-Blind MMStar (n=15)                  22201.0
                   JS-Blind VQA (n=10)                     22201.0
                   JS-Blind VQA (n=15)                     22201.0
                   SFT-Blind MMStar                        22201.0
                   SFT-Blind VQA                           22201.0

                                                               \
dataset
category                                   instance reasoning
model              finetuned
InternVL 3.5 (8B)  JS VQA (GT)                        38025.0
                   JS-Blind MMStar (n=15)             38025.0
                   JS-Blind VQA (n=10)                38025.0
                   JS-Blind VQA (n=15)                38025.0
                   SFT-Blind MMStar (n=15)            38025.0
                   SFT-Blind VQA                      38025.0
                   SFT-VQA                            38025.0
LLaVA‑Mistral (7B) JS VQA (GT)                        38025.0
                   JS-Blind MMStar (n=15)             38025.0
                   JS-Blind VQA (n=10)                38025.0
                   JS-Blind VQA (n=15)                38025.0
                   SFT-Blind MMStar                   38025.0
                   SFT-Blind VQA                      38025.0
                   SFT-VQA                            38025.0
Qwen3‑VL (4B)      JS VQA (GT)                        38025.0
                   JS-Blind MMStar (n=15)             38025.0
                   JS-Blind VQA (n=10)                38025.0
                   JS-Blind VQA (n=15)                38025.0
                   SFT-Blind VQA                      38025.0
                   SFT-VQA                            38025.0
Qwen3‑VL (8B)      JS VQA (GT)                        38025.0
                   JS-Blind MMStar (n=15)             38025.0
                   JS-Blind VQA (n=10)                38025.0
                   JS-Blind VQA (n=15)                38025.0
                   SFT-Blind MMStar                   38025.0
                   SFT-Blind VQA                      38025.0

                                                                       \
dataset
category                                   logical reasoning     math
model              finetuned
InternVL 3.5 (8B)  JS VQA (GT)                       51984.0  18500.0
                   JS-Blind MMStar (n=15)            51984.0  18500.0
                   JS-Blind VQA (n=10)               51984.0  18500.0
                   JS-Blind VQA (n=15)               51984.0  18500.0
                   SFT-Blind MMStar (n=15)           51984.0  18500.0
                   SFT-Blind VQA                     51984.0  18500.0
                   SFT-VQA                           51984.0  18500.0
LLaVA‑Mistral (7B) JS VQA (GT)                       51984.0  62500.0
                   JS-Blind MMStar (n=15)            51984.0  62500.0
                   JS-Blind VQA (n=10)               51984.0  62500.0
                   JS-Blind VQA (n=15)               51984.0  62500.0
                   SFT-Blind MMStar                  51984.0  62500.0
                   SFT-Blind VQA                     51984.0  62500.0
                   SFT-VQA                           51984.0  62500.0
Qwen3‑VL (4B)      JS VQA (GT)                       51984.0  62500.0
                   JS-Blind MMStar (n=15)            51984.0  62500.0
                   JS-Blind VQA (n=10)               51984.0  62500.0
                   JS-Blind VQA (n=15)               51984.0  62500.0
                   SFT-Blind VQA                     51984.0  62500.0
                   SFT-VQA                           51984.0  62500.0
Qwen3‑VL (8B)      JS VQA (GT)                       51984.0  62500.0
                   JS-Blind MMStar (n=15)            51984.0  62500.0
                   JS-Blind VQA (n=10)               51984.0  62500.0
                   JS-Blind VQA (n=15)               51984.0  62500.0
                   SFT-Blind MMStar                  51984.0  62500.0
                   SFT-Blind VQA                     51984.0  62500.0


dataset
category                                   science & technology
model              finetuned
InternVL 3.5 (8B)  JS VQA (GT)                              NaN
                   JS-Blind MMStar (n=15)                   NaN
                   JS-Blind VQA (n=10)                      NaN
                   JS-Blind VQA (n=15)                      NaN
                   SFT-Blind MMStar (n=15)                  NaN
                   SFT-Blind VQA                            NaN
                   SFT-VQA                                  NaN
LLaVA‑Mistral (7B) JS VQA (GT)                          62001.0
                   JS-Blind MMStar (n=15)               62001.0
                   JS-Blind VQA (n=10)                  62001.0
                   JS-Blind VQA (n=15)                  62001.0
                   SFT-Blind MMStar                     62001.0
                   SFT-Blind VQA                        62001.0
                   SFT-VQA                              62001.0
Qwen3‑VL (4B)      JS VQA (GT)                          62001.0
                   JS-Blind MMStar (n=15)               62001.0
                   JS-Blind VQA (n=10)                  62001.0
                   JS-Blind VQA (n=15)                  62001.0
                   SFT-Blind VQA                        62001.0
                   SFT-VQA                              62001.0
Qwen3‑VL (8B)      JS VQA (GT)                          62001.0
                   JS-Blind MMStar (n=15)               62001.0
                   JS-Blind VQA (n=10)                  62001.0
                   JS-Blind VQA (n=15)                  62001.0
                   SFT-Blind MMStar                     62001.0
                   SFT-Blind VQA                        62001.0

In [ ]:
vv = VQAResults()   
test_model = vv.test_model 
vqadf, vqapt = vv.finetuning_effect(test_model) 
vqadf = vqadf.melt(id_vars=['finetuned', 'family', 'model_size', 'question_id', 'answer_type', 'question_type'], value_vars=['delta_acc', 'delta_sim'], var_name='score_type', value_name='delta') 
vqadf['dataset'] = 'VQAv2'

   Loading VQA annotations from /home/work/yuna/VLMEval/data/v2_mscoco_val2014_annotations.json...
   ✓ Loaded 214354 VQA annotations
[]
[]

In [103]:
finetuned_results = pd.concat([dfdf, df, vqadf]) 
finetuned_results.dropna(axis=1)

                     finetuned  delta dataset
0                  JS VQA (GT)    0.0  MMStar
1                  JS VQA (GT)  100.0  MMStar
2                  JS VQA (GT)    0.0  MMStar
3                  JS VQA (GT)    0.0  MMStar
4                  JS VQA (GT)  100.0  MMStar
...                        ...    ...     ...
259995     JS-Blind VQA (n=10)    0.0   VQAv2
259996  JS-Blind MMStar (n=15)    0.0   VQAv2
259997        SFT-Blind MMStar    0.0   VQAv2
259998           SFT-Blind VQA    0.0   VQAv2
259999                 SFT-VQA    0.0   VQAv2

[6610623 rows x 3 columns]

In [ ]:
finetuned_results.pivot_table( 
            index=['family','finetuned',  'model_size',  ], #  'family',
            columns=['dataset', 'answer_type','score_type'],  # 
            values=['delta'], 
            aggfunc='mean' 
        )

Empty DataFrame
Columns: []
Index: []

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,10))

ax = sns.heatmap(
    df.pivot_table(
        index=['model', 'regime'], 
        columns=['category'], 
        values=['delta'], 
        aggfunc='mean'
    ).droplevel(0, axis=1),
    annot=True,
    fmt=".1f",
    cmap="vidiris", # RdBu_r
    center=0,
    linewidths=0.5,
    cbar_kws={"label": "Δ Score "}
)

# ax.set_xticklabels(categories, rotation=0)
# ax.set_yticklabels(models, rotation=0)

plt.title("Blind Training Improves Reasoning-Oriented Categories", pad=10)
plt.tight_layout()
plt.show()

KeyError: 'delta'

In [ ]:
df.category.unique()

### Correlations

In [ ]:
res_HH, res_MM, res_HM  = get_agreements(human_vqa, model_vqa, n_boot=0)  # accuarcy 
corr_mat = get_all_cm(res_HH, res_MM, res_HM )
acc_corr = res_HM['corr_mat'].mean().sort_values().reset_index(name='acc_corr') 
plot_unified_agreement_heatmap(corr_mat, res_HH['corr_mat'].columns, res_MM['corr_mat'].columns, 'Human–Model Agreement (Accuracy)', '/home/work/yuna/HPA/evaluation/analysis/figures/agreement-acc.png') 
acc = pd.concat([result_to_df(res_HH), result_to_df(res_MM), result_to_df(res_HM)]) 

res_HH['corr_mat'].mean().reset_index().to_csv('./corr/acc-humans-n6.csv', encoding="utf-8-sig")
res_MM['corr_mat'].mean().reset_index().to_csv('./corr/acc-models-toM.csv', encoding="utf-8-sig")
res_HM['corr_mat'].mean().reset_index().to_csv('./corr/acc-models-toH-n6.csv', encoding="utf-8-sig")

In [ ]:
res_HH, res_MM, res_HM  =  get_agreements(human_vqa, model_vqa, 'answer_similarity', n_boot=0) 
corr_mat = get_all_cm(res_HH, res_MM, res_HM ) 
sim_corr = res_HM['corr_mat'].mean().sort_values().reset_index(name='sim_corr') 
pcorr = pd.merge(acc_corr, sim_corr, on =['model']) 
acc = pd.concat([acc, result_to_df(res_HH), result_to_df(res_MM), result_to_df(res_HM)])
plot_unified_agreement_heatmap(corr_mat,  res_HH['corr_mat'].columns, res_MM['corr_mat'].columns, 'Human–Model Agreement (Emb Similarity)', '/home/work/yuna/HPA/evaluation/analysis/figures/agreement-sim.png') 
transform_corr_table(acc) # .to_latex('./tables/appendix/3_spearman-interrater-vqa-finetuned.tex', float_format="%.3f")

In [ ]:

if isinstance(mg_df.columns, pd.MultiIndex):
    mg_df.columns = ['_'.join(str(c) for c in col if c != '') for col in mg_df.columns.values]

In [ ]:
# from utils.plots import scatterplot, get_family, parse_size 
from utils.plots import scatterplot_finetuned 
import pandas as pd
from utils.corr import corr_by_regime

exclude_models = [
    "LLaVA‑Vicuna‑7B", "Qwen3‑VL‑2B", "LLaVA‑1.5‑7B",
    "InternVL3.5‑1B", "InternVL3.5‑2B", "InternVL3.5‑4B",
]
pcorr = pd.merge(acc_corr, sim_corr, on =['model']) 
pcorr= pd.merge(pcorr.reset_index(), mg_df.reset_index(), on=['model'])  
pcorr = pcorr[~pcorr['model'].str.contains('MMStar')]
pcorr = pcorr[['model', 'acc_corr', 'sim_corr', 'MG_Acc', 'MG_S']]

pcorr = pcorr[~pcorr['model'].str.contains('|'.join(exclude_models))]
corr_by_regime(pcorr).to_latex('./tables/appendix/finetuned-pearson-r.tex', float_format="%.1f")    

for fam in pcorr.family.unique(): 
    scatterplot_finetuned(pcorr[(pcorr['family'] == fam) ] , x_col='acc_corr', y_col='MG_Acc', title=f'{fam} accuracy') # 
    scatterplot_finetuned(pcorr[(pcorr['family'] == fam) ] , x_col='sim_corr', y_col='MG_S', title=f'{fam} similairty') #

In [ ]:
plt.figure(figsize=(8,8))
sns.heatmap(
    pt,
    annot=True,
    fmt=".2f",
    cmap="viridis",
    # vmin=0, vmax=1,
    linewidths=0.5
)
plt.ylabel("Model")
plt.xlabel("Spurious correlation type")
plt.title("Accuracy by model and spurious correlation type")
plt.tight_layout()
plt.show() # spu-corr-finetune.png

In [ ]:

trainh = human_mc[human_mc['participant_id'].isin(pids)] 
human_mc = human_mc[~human_mc['participant_id'].isin(pids)] 
len(trainh.participant_id.unique()) , len(human_mc.participant_id.unique())

In [ ]:

 
df2 = pd.concat([df, meta], axis=1)
pt = (
    df2.groupby(['model', 'trainer', 'supervision', 'dataset'])['delta']
       .mean()
       .unstack(['supervision', 'dataset'])
       .round(3)
)