In [ ]:
from analysis.utils.score import get_summary, extract_mc_choice, MODEL_DISPLAY_MAP 

okvqa = get_summary('okvqa').drop_duplicates(subset=['condition', 'question_id', 'model']) 
okvqa.pivot_table(index='model', columns='condition', values=['question_id', 'correct'], aggfunc='nunique')
okvqa.pivot_table(index='model', columns='condition', values=['correct'], aggfunc='mean')

14

In [ ]:
correct_qids = okvqa[(okvqa['correct'] == 100) & (okvqa['question_type'] == okvqa.question_type.unique()[1])].question_id.unique() 
df = (okvqa[okvqa['question_id'] == correct_qids[1]]
      .sort_values(['correct', 'condition']))
print(df.iloc[0]['question'], '\n',
      'Answers:',df.iloc[0]['answers'], '\n',
      'answer_type: ', df.iloc[0]['answer_type'],  '\n',
      'question_type: ', df.iloc[0]['question_type'],  )
pivoted = df.pivot(index=['condition'], columns='model', values='output') 
pivoted

What south american country usually has this climate?
 Answers: ['brazil', 'brazil', 'brazil', 'brazil', 'brazil', 'brazil', 'africa', 'africa', 'ecuador', 'ecuador']
 answer_type:  other
 question_type:  Plants and Animals

model,InternVL3_5-1B,InternVL3_5-2B,InternVL3_5-8B,Qwen3-VL-2B-Instruct,Qwen3-VL-4B-Instruct,Qwen3-VL-8B-Instruct,llava-1.5-7b-hf,llava-v1.6-mistral-7b-hf,llava-v1.6-vicuna-7b-hf
condition,,,,,,,,,
,brazil,Paraguay,brazil,argentina,brazil,brazil,Brazil,Argentina,Brazil
inst blind,Brazil,Argentina,Brazil,Argentina,brazil,Chile,Brazil,Brazil,Brazil

In [ ]:
okvqa_summary = okvqa.pivot_table(index=['answer_type', 'question_type'], columns=['condition'], values=['correct'], aggfunc='mean')
okvqa_summary = okvqa_summary.sort_values([('correct', 'inst blind')], ascending=False)
okvqa_summary

                                                        correct
condition                                                       inst blind
answer_type question_type
other       Weather and Climate                       63.631352  25.942734
            Brands, Companies and Products            57.153359  24.051595
            People and Everyday life                  57.152700  23.026562
            Other                                     59.276126  21.990402
            Objects, Material and Clothing            53.915421  20.812087
            Cooking and Food                          57.078675  20.754242
            Science and Technology                    55.956614  20.488613
            Geography, History, Language and Culture  56.979669  19.569610
            Plants and Animals                        55.388398  19.280051
            Vehicles and Transportation               51.815375  19.246892
            Sports and Recreation                     60.407074  19.069128

In [ ]:
textvqa = get_summary('textvqa').drop_duplicates(subset=['condition', 'question_id', 'model']) 
textvqa.pivot_table(index='model', columns='condition', values=['question_id', 'correct'], aggfunc='nunique')
textvqa.pivot_table(index='model', columns='condition', values=['correct'], aggfunc='mean')

In [ ]:
correct_qids = textvqa[textvqa['correct'] == 100].question_id.unique()
df = (textvqa[textvqa['question_id'] == correct_qids[0]]
      .sort_values(['correct', 'condition']))
print(df.iloc[0]['question'], '\n',
      'Answers:',df.iloc[0]['answers'], '\n',
      'image_classes: ', df.iloc[0]['image_classes'],  )
pivoted = df.pivot(index=['condition'], columns='model', values='output')
pivoted

Question: how long has the drink on the right been aged? Answer the question using a single word or phrase.
Answer:
Note: No images are provided. For each question, imagine an appropriate image exists and answer based on the most common or universal scenario.
 Answers: ['10 years', '10 year', '10 years', '10 years ', '10 years', '10 years', '10 years', '10 years', 'martial arts', '10']
 image_classes:  ['Beer', 'Drink', 'Bottle', 'Wine']

model,InternVL3_5-1B,InternVL3_5-2B,InternVL3_5-4B,InternVL3_5-8B,Qwen3-VL-2B-Instruct,Qwen3-VL-4B-Instruct,Qwen3-VL-8B-Instruct,llava-1.5-7b-hf,llava-v1.6-mistral-7b-hf,llava-v1.6-vicuna-7b-hf
condition,,,,,,,,,,
,10 years,10 years,10 years,10 years,10 years,10 years,10 years,10 years,10 years,10 years
inst blind,12 hours,18 months,7 days.,10 years,12 months,12 years,10 years,10 years,0,10 years

In [54]:
textvqa.pivot_table(index=['model'], columns=['condition'], values=['correct'], aggfunc='mean').sort_values([('correct', 'inst blind')], ascending=False)

                           correct
condition                          inst blind
model
InternVL3_5-8B            72.86646    9.23312
Qwen3-VL-8B-Instruct      77.10182    7.37970
InternVL3_5-4B            69.74628    6.79310
InternVL3_5-2B            69.82636    5.98642
llava-v1.6-mistral-7b-hf  62.89284    5.83972
Qwen3-VL-4B-Instruct      76.55970    5.71306
llava-v1.6-vicuna-7b-hf   62.23954    5.64640
Qwen3-VL-2B-Instruct      74.99972    4.79978
llava-1.5-7b-hf           46.36624    4.55978
InternVL3_5-1B            65.49302    4.08642