In [16]:
import pandas as pd 
from glob import glob 
root_dir = '/home/work/yuna/HPA/evaluation/scored'

model_names = [
            "OpenGVLab/InternVL3_5-8B",
            "OpenGVLab/InternVL3_5-2B",
            "OpenGVLab/InternVL3_5-4B",
            "OpenGVLab/InternVL3_5-1B",

            "Qwen/Qwen3-VL-2B-Instruct", 
            "Qwen/Qwen3-VL-4B-Instruct", 
            "Qwen/Qwen3-VL-8B-Instruct",

            "llava-hf/llava-1.5-7b-hf", 
            "llava-hf/llava-v1.6-vicuna-7b-hf", 
            "llava-hf/llava-v1.6-mistral-7b-hf", 

            "Qwen/Qwen3-8B-Base", 
            "Qwen/Qwen3-4B-Base", 
            "Qwen/Qwen3-1.7B-Base" , 
            "Qwen/Qwen3-0.6B-Base" # doesnt work 
]

def find_matching(f, targets): 
    for t in targets : 
        if t in f : 
            f = f.replace(f'{t}', '')   
            return t, f 
    print(f"cannot find matching {f} in {targets}") 

def get_summary(dataset='mmstar'): 
    # df = df.groupby(['model', 'folder', 'condition'])['correct'].mean()

    files = glob(f"{root_dir}/*/*{dataset}*.jsonl")  + glob(f"{root_dir}/*/*/*/{dataset}*.jsonl")

    dfs= []
    for f in files: 
        try: 
            df = pd.read_json(f, lines=True)
            df['folder'] = f.split('/')[-2]
            df['model'], f = find_matching(f, [model.split('/')[-1] for model in model_names])  
            df['condition'] = f.split('/')[-1][:-6].replace(f'_', ' ').replace(f'{dataset}', '').strip()
            dfs.append(df)
        except Exception as e: 
            print(e)
    df = pd.concat(dfs)
    print(len(files) ) 

    pt = df.pivot_table(
        index=['model', 'folder'], 
        columns=['condition'], 
        values=['correct'],
        aggfunc=['mean', 'count']
    )
    # Round the "mean" rows/columns to 2 decimal places
    pt = pt.round(4)
    pt.to_csv(f"./summary_{dataset}.csv")
    return df , pt

In [25]:
!python /home/work/yuna/HPA/evaluation/process_raw_human_responses.py

============================================================
📊 Processing Raw Human Responses
   Session: s1
   Data dir: /home/work/yuna/HPA/data/humans/all_results_20251206_154732
============================================================

📚 Loading annotations...

============================================================
Processing VQA (text) responses...
============================================================
============================================================
📋 ANSWER PREPROCESSING PIPELINE
============================================================

[1/5] Loading data...
✓ Loaded 641 questions from /home/work/yuna/HPA/dataset/questions/s1.csv
/home/work/yuna/HPA/data/humans/all_results_20251206_154732/1ed1a464_20251204_110002/answers.csv is incomplete, skip
/home/work/yuna/HPA/data/humans/all_results_20251206_154732/99f271ae_20251203_111155/answers.csv is incomplete, skip
✓ Loaded 9622 responses from 15 files

[2/5] Translating Korean answers...
✓ Loaded 1381 cached translations from /home/work/yuna/HPA/preprocessing/translation_cache.json
❌ OpenAI package not installed. Run: pip install openai
⚠ Skipping translation (no API client)

[3/5] Normalizing answers...
   ✓ /home/work/yuna/HPA/evaluation/scored/humans/cleaned_n15_choice.json
   ✓ /home/work/yuna/HPA/evaluation/scored/humans/cleaned_n15_text.json

[5/5] Saving outputs...
   ✓ /home/work/yuna/HPA/evaluation/scored/humans/preprocessing_stats.json

============================================================
📊 PREPROCESSING SUMMARY
============================================================
   total_responses: 9622
   total_questions: 641
   total_participants: 15
   korean_translated: 0
   unique_answers: 1244
============================================================
   Loading VQA annotations from /home/work/yuna/VLMEval/data/v2_mscoco_val2014_annotations.json...
   ✓ Loaded 214354 VQA annotations
   Found 374 VQA questions
Processing VQA: 100%|███████████████████████| 374/374 [00:00<00:00, 1302.88it/s]

   ✓ Saved: /home/work/yuna/HPA/evaluation/scored/humans/human_vqa_per_question.jsonl
   ✓ Saved: /home/work/yuna/HPA/evaluation/scored/humans/human_vqa_stats.json

============================================================
Processing MC (choice) responses...
============================================================
   Found 374 VQA questions
   Found 223 MC questions
Processing MC: 100%|████████████████████████| 223/223 [00:00<00:00, 9828.51it/s]

   ✓ Saved: /home/work/yuna/HPA/evaluation/scored/humans/human_mc_per_question.jsonl
   ✓ Saved: /home/work/yuna/HPA/evaluation/scored/humans/human_mc_stats.json

============================================================
📈 Summary
============================================================
VQA Questions: 374
  Mean Accuracy: 0.0571
  Mean Confidence: 0.6629
  Correlation (Conf-Acc): -0.0910

MC Questions: 223
  Mean Accuracy: 0.2739
  Mean Confidence: 0.5910
  Correlation (Conf-Acc): 0.0929

✅ Processing complete! Results saved to: /home/work/yuna/HPA/evaluation/scored/humans

In [71]:
!python /home/work/yuna/HPA/evaluation/score_results.py  --input_dir finetuned  
!python /home/work/yuna/HPA/evaluation/score_results.py  --input_dir pretrained

11424.00s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Found 5 files to score
📊 Scoring: /home/work/yuna/HPA/evaluation/results/finetuned/Qwen3-VL-4B-Instruct/A1_JS_vqa_n15_blind_inst/mmstar.jsonl
   ✓ Saved scored file: /home/work/yuna/HPA/evaluation/scored/finetuned/Qwen3-VL-4B-Instruct/A1_JS_vqa_n15_blind_inst/mmstar.jsonl

📈 Results:
   Accuracy: 0.5860 (879/1500)

   Per-category:
      coarse perception: 0.704 (176/250)
      instance reasoning: 0.700 (175/250)
      logical reasoning: 0.596 (149/250)
      math: 0.564 (141/250)
      fine-grained perception: 0.552 (138/250)
      science & technology: 0.400 (100/250)
📊 Scoring: /home/work/yuna/HPA/evaluation/results/finetuned/Qwen3-VL-4B-Instruct/A1_JS_vqa_n15_blind_inst/mmstar_inst_blind.jsonl
   ✓ Saved scored file: /home/work/yuna/HPA/evaluation/scored/finetuned/Qwen3-VL-4B-Instruct/A1_JS_vqa_n15_blind_inst/mmstar_inst_blind.jsonl

📈 Results:
   Accuracy: 0.2673 (401/1500)

   Per-category:
      math: 0.380 (95/250)
      coarse perception: 0.280 (70/250)
      fine-grained perception: 0.276 (69/250)
      instance reasoning: 0.276 (69/250)
      logical reasoning: 0.232 (58/250)
      science & technology: 0.160 (40/250)
📊 Scoring: /home/work/yuna/HPA/evaluation/results/finetuned/Qwen3-VL-4B-Instruct/A1_JS_vqa_n15_blind_inst/spubench.jsonl
   ✓ Saved scored file: /home/work/yuna/HPA/evaluation/scored/finetuned/Qwen3-VL-4B-Instruct/A1_JS_vqa_n15_blind_inst/spubench.jsonl

📈 Results:
   Accuracy: 0.7426 (1359/1830)

   Per-category:
      Unknown: 0.743 (1359/1830)
📊 Scoring: /home/work/yuna/HPA/evaluation/results/finetuned/Qwen3-VL-4B-Instruct/A1_JS_vqa_n15_blind_inst/vqa_1k.jsonl
📂 Loading VQA annotations (this may take a moment)...
   ✓ Loaded 214354 question annotations
   ✓ Saved scored file: /home/work/yuna/HPA/evaluation/scored/finetuned/Qwen3-VL-4B-Instruct/A1_JS_vqa_n15_blind_inst/vqa_1k.jsonl

📈 Results:
   Accuracy: 0.7500 (750/1000)

   Per-category:
      is the man: 1.000 (9/9)
      does this: 1.000 (14/14)
      is there a: 1.000 (21/21)
      is this an: 1.000 (5/5)
      is there: 1.000 (13/13)
      are they: 1.000 (6/6)
      does the: 1.000 (14/14)
      what is the person: 1.000 (2/2)
      what is the color of the: 1.000 (5/5)
      could: 1.000 (7/7)
      is it: 1.000 (15/15)
      has: 1.000 (2/2)
      is that a: 1.000 (4/4)
      was: 1.000 (2/2)
      are there: 1.000 (10/10)
      do you: 1.000 (4/4)
      what sport is: 1.000 (5/5)
      are there any: 1.000 (9/9)
      what room is: 1.000 (2/2)
      is this person: 1.000 (1/1)
      is the person: 1.000 (1/1)
      is this a: 0.976 (40/41)
      is the: 0.943 (83/88)
      what color: 0.917 (11/12)
      what color are the: 0.909 (10/11)
      is this: 0.875 (35/40)
      what color is: 0.875 (7/8)
      what color is the: 0.847 (50/59)
      do: 0.833 (10/12)
      are: 0.833 (10/12)
      are these: 0.818 (9/11)
      are the: 0.810 (17/21)
      can you: 0.800 (4/5)
      what animal is: 0.800 (4/5)
      is: 0.769 (10/13)
      what is the name: 0.750 (3/4)
      what number is: 0.750 (3/4)
      none of the above: 0.730 (27/37)
      what are: 0.700 (7/10)
      how many: 0.682 (58/85)
      is the woman: 0.667 (2/3)
      is he: 0.667 (2/3)
      what is the: 0.654 (34/52)
      what is on the: 0.615 (8/13)
      what: 0.607 (51/84)
      what does the: 0.600 (9/15)
      what is this: 0.600 (6/10)
      what kind of: 0.583 (14/24)
      how many people are: 0.571 (4/7)
      what is: 0.548 (17/31)
      what is in the: 0.545 (6/11)
      what are the: 0.538 (7/13)
      what type of: 0.526 (10/19)
      who is: 0.500 (3/6)
      which: 0.500 (7/14)
      how many people are in: 0.500 (2/4)
      where is the: 0.467 (7/15)
      what is the man: 0.385 (5/13)
      where are the: 0.286 (2/7)
      what is the woman: 0.250 (1/4)
      how: 0.250 (2/8)
      why is the: 0.200 (1/5)
      why: 0.143 (1/7)
      what time: 0.000 (0/3)
📊 Scoring: /home/work/yuna/HPA/evaluation/results/finetuned/Qwen3-VL-4B-Instruct/A1_JS_vqa_n15_blind_inst/vqa_1k_inst_blind.jsonl
   ✓ Saved scored file: /home/work/yuna/HPA/evaluation/scored/finetuned/Qwen3-VL-4B-Instruct/A1_JS_vqa_n15_blind_inst/vqa_1k_inst_blind.jsonl

📈 Results:
   Accuracy: 0.3300 (330/1000)

   Per-category:
      has: 1.000 (2/2)
      is this person: 1.000 (1/1)
      is the person: 1.000 (1/1)
      are these: 0.818 (9/11)
      can you: 0.800 (4/5)
      is that a: 0.750 (3/4)
      does this: 0.714 (10/14)
      do: 0.667 (8/12)
      are they: 0.667 (4/6)
      is it: 0.667 (10/15)
      are: 0.667 (8/12)
      is he: 0.667 (2/3)
      are there any: 0.667 (6/9)
      does the: 0.643 (9/14)
      is the: 0.614 (54/88)
      is this a: 0.610 (25/41)
      is this: 0.600 (24/40)
      what is the color of the: 0.600 (3/5)
      what sport is: 0.600 (3/5)
      could: 0.571 (4/7)
      is the man: 0.556 (5/9)
      is: 0.538 (7/13)
      is there a: 0.524 (11/21)
      was: 0.500 (1/2)
      do you: 0.500 (2/4)
      are the: 0.476 (10/21)
      is there: 0.462 (6/13)
      none of the above: 0.405 (15/37)
      is this an: 0.400 (2/5)
      are there: 0.400 (4/10)
      is the woman: 0.333 (1/3)
      how many: 0.306 (26/85)
      how many people are: 0.286 (2/7)
      what color is: 0.250 (2/8)
      what color: 0.250 (3/12)
      how many people are in: 0.250 (1/4)
      what kind of: 0.167 (4/24)
      what type of: 0.158 (3/19)
      what is on the: 0.154 (2/13)
      what are the: 0.154 (2/13)
      which: 0.143 (2/14)
      what color is the: 0.136 (8/59)
      what is the: 0.115 (6/52)
      what: 0.107 (9/84)
      what are: 0.100 (1/10)
      what is: 0.097 (3/31)
      what does the: 0.067 (1/15)
      where is the: 0.067 (1/15)
      what is the woman: 0.000 (0/4)
      what is in the: 0.000 (0/11)
      what is this: 0.000 (0/10)
      why: 0.000 (0/7)
      what is the name: 0.000 (0/4)
      who is: 0.000 (0/6)
      what color are the: 0.000 (0/11)
      what is the person: 0.000 (0/2)
      what is the man: 0.000 (0/13)
      why is the: 0.000 (0/5)
      where are the: 0.000 (0/7)
      how: 0.000 (0/8)
      what animal is: 0.000 (0/5)
      what number is: 0.000 (0/4)
      what time: 0.000 (0/3)
      what room is: 0.000 (0/2)

============================================================
✓ Processed 5 files
============================================================

============================================================
📊 SUMMARY
============================================================
condition                                                              _inst_blind
model                                              dataset
Qwen/Qwen3-VL-4B-Instruct/A1_JS_vqa_n15_blind_inst mmstar    0.586000     0.267333
                                                   spubench  0.742623     0.000000
                                                   vqa_1k    0.750000     0.330000

✓ Detailed results: /home/work/yuna/HPA/evaluation/scored/finetuned/scored_results.json
✓ Summary CSV: /home/work/yuna/HPA/evaluation/scored/finetuned/summary.csv

In [76]:
model_results = {}
for ds in ['mmstar', 'spubench', 'vqa_5k', 'vqa_1k']: 
    model_results[ds], pv = get_summary(ds)

cannot find matching /home/work/yuna/HPA/evaluation/scored/pretrained/Qwen3-0.6B_mmstar.jsonl in ['InternVL3_5-8B', 'InternVL3_5-2B', 'InternVL3_5-4B', 'InternVL3_5-1B', 'Qwen3-VL-2B-Instruct', 'Qwen3-VL-4B-Instruct', 'Qwen3-VL-8B-Instruct', 'llava-1.5-7b-hf', 'llava-v1.6-vicuna-7b-hf', 'llava-v1.6-mistral-7b-hf', 'Qwen3-8B-Base', 'Qwen3-4B-Base', 'Qwen3-1.7B-Base', 'Qwen3-0.6B-Base']
cannot unpack non-iterable NoneType object
45
cannot find matching /home/work/yuna/HPA/evaluation/scored/pretrained/Qwen3-4B_spubench.jsonl in ['InternVL3_5-8B', 'InternVL3_5-2B', 'InternVL3_5-4B', 'InternVL3_5-1B', 'Qwen3-VL-2B-Instruct', 'Qwen3-VL-4B-Instruct', 'Qwen3-VL-8B-Instruct', 'llava-1.5-7b-hf', 'llava-v1.6-vicuna-7b-hf', 'llava-v1.6-mistral-7b-hf', 'Qwen3-8B-Base', 'Qwen3-4B-Base', 'Qwen3-1.7B-Base', 'Qwen3-0.6B-Base']
cannot unpack non-iterable NoneType object
40
cannot find matching /home/work/yuna/HPA/evaluation/scored/pretrained/Qwen3-4B_vqa_5k.jsonl in ['InternVL3_5-8B', 'InternVL3_5-2B', 'InternVL3_5-4B', 'InternVL3_5-1B', 'Qwen3-VL-2B-Instruct', 'Qwen3-VL-4B-Instruct', 'Qwen3-VL-8B-Instruct', 'llava-1.5-7b-hf', 'llava-v1.6-vicuna-7b-hf', 'llava-v1.6-mistral-7b-hf', 'Qwen3-8B-Base', 'Qwen3-4B-Base', 'Qwen3-1.7B-Base', 'Qwen3-0.6B-Base']
cannot unpack non-iterable NoneType object
44
cannot find matching /home/work/yuna/HPA/evaluation/scored/pretrained/Qwen3-4B_vqa_1k.jsonl in ['InternVL3_5-8B', 'InternVL3_5-2B', 'InternVL3_5-4B', 'InternVL3_5-1B', 'Qwen3-VL-2B-Instruct', 'Qwen3-VL-4B-Instruct', 'Qwen3-VL-8B-Instruct', 'llava-1.5-7b-hf', 'llava-v1.6-vicuna-7b-hf', 'llava-v1.6-mistral-7b-hf', 'Qwen3-8B-Base', 'Qwen3-4B-Base', 'Qwen3-1.7B-Base', 'Qwen3-0.6B-Base']
cannot unpack non-iterable NoneType object
41

In [111]:
human_mc=pd.read_csv('/home/work/yuna/HPA/evaluation/scored/humans/human_mc_per_question.csv')
human_mc['model'] = "humans" 
human_mc['folder'] = "humans" 
human_mc.rename(columns={'mean_accuracy': 'correct'}, inplace=True) 
human_mc['condition'] = "inst blind" 
human_mc.groupby('category')['correct'].mean()

category
coarse perception          0.279781
fine-grained perception    0.266330
instance reasoning         0.284211
logical reasoning          0.270775
Name: correct, dtype: float64

In [116]:
# matching pids for human-model comparison 
qids = human_mc.pid.unique()
model_mc = model_results['mmstar']
print(len(qids))
mmstar_human_comparison = pd.concat([model_mc[model_mc['pid'].isin(qids)] , human_mc])
pt = mmstar_human_comparison.pivot_table(
    index=['model', 'folder'], 
    columns=['condition'], 
    values=['correct'],
    aggfunc=['mean', 'count']
)
# Round the "mean" rows/columns to 2 decimal places
pt = pt.round(4)
pt.to_csv(f'./mmstar_human_comparison.csv')
pt

223

                                                                       mean  \
                                                                    correct
condition
model                    folder
InternVL3_5-1B           pretrained                                0.434978
InternVL3_5-2B           pretrained                                0.511211
InternVL3_5-4B           pretrained                                 0.61435
InternVL3_5-8B           pretrained                                0.609865
Qwen3-8B-Base            pretrained                                0.197309
Qwen3-VL-2B-Instruct     pretrained                                0.560538
Qwen3-VL-4B-Instruct     A0_SFT_vqa_gt                             0.605381
                         A1_JS_vqa_blind_n10                       0.596413
                         A1_JS_vqa_n15_blind_inst                   0.58296
                         D1_JS_mmstar_blind                        0.591928
                         pretrained                                0.632287
Qwen3-VL-8B-Instruct     A0_JS_vqa_gt_10                                NaN
                         A0_SFT_vqa_gt                             0.672646
                         A1_JS_vqa_blind_n10                       0.663677
                         D0_SFT_mmstar_blind                       0.641256
                         Qwen3-VL-8B-Instruct_A1_JS_vqa_blind_n15  0.654709
                         pretrained                                0.672646
humans                   humans                                         NaN
llava-v1.6-mistral-7b-hf pretrained                                0.394619

                                                                             \

condition                                                             blind
model                    folder
InternVL3_5-1B           pretrained                                0.295964
InternVL3_5-2B           pretrained                                 0.26009
InternVL3_5-4B           pretrained                                0.269058
InternVL3_5-8B           pretrained                                0.331839
Qwen3-8B-Base            pretrained                                     NaN
Qwen3-VL-2B-Instruct     pretrained                                0.219731
Qwen3-VL-4B-Instruct     A0_SFT_vqa_gt                                  NaN
                         A1_JS_vqa_blind_n10                       0.286996
                         A1_JS_vqa_n15_blind_inst                       NaN
                         D1_JS_mmstar_blind                         0.29148
                         pretrained                                0.313901
Qwen3-VL-8B-Instruct     A0_JS_vqa_gt_10                                NaN
                         A0_SFT_vqa_gt                                  NaN
                         A1_JS_vqa_blind_n10                            NaN
                         D0_SFT_mmstar_blind                            NaN
                         Qwen3-VL-8B-Instruct_A1_JS_vqa_blind_n15       NaN
                         pretrained                                0.295964
humans                   humans                                         NaN
llava-v1.6-mistral-7b-hf pretrained                                     NaN

                                                                              \

condition                                                         inst blind
model                    folder
InternVL3_5-1B           pretrained                                 0.282511
InternVL3_5-2B           pretrained                                 0.224215
InternVL3_5-4B           pretrained                                 0.251121
InternVL3_5-8B           pretrained                                 0.331839
Qwen3-8B-Base            pretrained                                      NaN
Qwen3-VL-2B-Instruct     pretrained                                 0.278027
Qwen3-VL-4B-Instruct     A0_SFT_vqa_gt                              0.295964
                         A1_JS_vqa_blind_n10                         0.29148
                         A1_JS_vqa_n15_blind_inst                   0.278027
                         D1_JS_mmstar_blind                          0.29148
                         pretrained                                  0.29148
Qwen3-VL-8B-Instruct     A0_JS_vqa_gt_10                            0.309417
                         A0_SFT_vqa_gt                              0.309417
                         A1_JS_vqa_blind_n10                        0.282511
                         D0_SFT_mmstar_blind                        0.327354
                         Qwen3-VL-8B-Instruct_A1_JS_vqa_blind_n15   0.300448
                         pretrained                                  0.32287
humans                   humans                                     0.273937
llava-v1.6-mistral-7b-hf pretrained                                 0.269058

                                                                    count  \
                                                                  correct
condition
model                    folder
InternVL3_5-1B           pretrained                                 223.0
InternVL3_5-2B           pretrained                                 223.0
InternVL3_5-4B           pretrained                                 223.0
InternVL3_5-8B           pretrained                                 223.0
Qwen3-8B-Base            pretrained                                 223.0
Qwen3-VL-2B-Instruct     pretrained                                 223.0
Qwen3-VL-4B-Instruct     A0_SFT_vqa_gt                              223.0
                         A1_JS_vqa_blind_n10                        223.0
                         A1_JS_vqa_n15_blind_inst                   223.0
                         D1_JS_mmstar_blind                         223.0
                         pretrained                                 223.0
Qwen3-VL-8B-Instruct     A0_JS_vqa_gt_10                              NaN
                         A0_SFT_vqa_gt                              223.0
                         A1_JS_vqa_blind_n10                        223.0
                         D0_SFT_mmstar_blind                        223.0
                         Qwen3-VL-8B-Instruct_A1_JS_vqa_blind_n15   223.0
                         pretrained                                 223.0
humans                   humans                                       NaN
llava-v1.6-mistral-7b-hf pretrained                                 223.0

                                                                          \

condition                                                          blind
model                    folder
InternVL3_5-1B           pretrained                                223.0
InternVL3_5-2B           pretrained                                223.0
InternVL3_5-4B           pretrained                                223.0
InternVL3_5-8B           pretrained                                223.0
Qwen3-8B-Base            pretrained                                  NaN
Qwen3-VL-2B-Instruct     pretrained                                223.0
Qwen3-VL-4B-Instruct     A0_SFT_vqa_gt                               NaN
                         A1_JS_vqa_blind_n10                       223.0
                         A1_JS_vqa_n15_blind_inst                    NaN
                         D1_JS_mmstar_blind                        223.0
                         pretrained                                223.0
Qwen3-VL-8B-Instruct     A0_JS_vqa_gt_10                             NaN
                         A0_SFT_vqa_gt                               NaN
                         A1_JS_vqa_blind_n10                         NaN
                         D0_SFT_mmstar_blind                         NaN
                         Qwen3-VL-8B-Instruct_A1_JS_vqa_blind_n15    NaN
                         pretrained                                223.0
humans                   humans                                      NaN
llava-v1.6-mistral-7b-hf pretrained                                  NaN



condition                                                         inst blind
model                    folder
InternVL3_5-1B           pretrained                                    223.0
InternVL3_5-2B           pretrained                                    223.0
InternVL3_5-4B           pretrained                                    223.0
InternVL3_5-8B           pretrained                                    223.0
Qwen3-8B-Base            pretrained                                      NaN
Qwen3-VL-2B-Instruct     pretrained                                    223.0
Qwen3-VL-4B-Instruct     A0_SFT_vqa_gt                                 223.0
                         A1_JS_vqa_blind_n10                           223.0
                         A1_JS_vqa_n15_blind_inst                      223.0
                         D1_JS_mmstar_blind                            223.0
                         pretrained                                    223.0
Qwen3-VL-8B-Instruct     A0_JS_vqa_gt_10                               223.0
                         A0_SFT_vqa_gt                                 223.0
                         A1_JS_vqa_blind_n10                           223.0
                         D0_SFT_mmstar_blind                           223.0
                         Qwen3-VL-8B-Instruct_A1_JS_vqa_blind_n15      223.0
                         pretrained                                    223.0
humans                   humans                                        223.0
llava-v1.6-mistral-7b-hf pretrained                                    223.0

In [67]:
human_vqa=pd.read_csv('/home/work/yuna/HPA/evaluation/scored/humans/human_vqa_per_question.csv')
# matching pids for human-model comparison 
human_vqa['model'] = "humans" 

qids = human_vqa.qid.unique()
print(len(qids))
model_vqa = model_results['vqa_1k'] 
model_vqa[model_vqa['question_id'].isin(qids)]

374

In [ ]:
pt = df.pivot_table(
    index=['model', 'folder'], 
    columns=['condition'], 
    values=['correct'],
    aggfunc=['mean', 'count']
)
# Round the "mean" rows/columns to 2 decimal places
pt = pt.round(4)

# MMStar

In [44]:
dfs = []
for filepath in glob("/home/work/yuna/HPA/results/swift/*mmstar*.jsonl"): 
    print(f"Evaluating: {filepath}")
    df = read_file(filepath) 
    dfs.append(df)
    # results = evaluate_results(filepath)
    # print_report(results)

Evaluating: /home/work/yuna/HPA/results/swift/llava-v1.6-mistral-7b-hf_mmstar.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/InternVL3_5-4B_mmstar_blind.jsonl
'output' cannot process /home/work/yuna/HPA/results/swift/InternVL3_5-4B_mmstar_blind.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/Qwen3-VL-4B-Instruct_mmstar_inst_blind.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/InternVL3_5-4B_mmstar_inst_blind.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/InternVL3_5-2B_mmstar_sys_inst_blind.jsonl
'output' cannot process /home/work/yuna/HPA/results/swift/InternVL3_5-2B_mmstar_sys_inst_blind.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/llava-v1.6-mistral-7b-hf_mmstar_inst_blind.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/Qwen3-VL-4B-Instruct_mmstar_blind.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/InternVL3_5-4B_mmstar.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/Qwen3-0.6B_mmstar.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/llava-v1.6-mistral-7b-hf_mmstar_blind.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/InternVL3_5-8B_mmstar_inst_blind.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/InternVL3_5-8B_mmstar.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/Qwen3-VL-4B-Instruct_mmstar.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/InternVL3_5-8B_mmstar_blind.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/Qwen3-VL-8B-Instruct_mmstar_inst_blind.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/Qwen3-VL-8B-Instruct_mmstar.jsonl
Evaluating: /home/work/yuna/HPA/results/swift/InternVL3_5-2B_mmstar_inst_blind.jsonl

In [54]:
df = pd.concat(dfs)
df = df[df['condition'] != '_blind']
results = df.groupby(['model_full', 'condition', 'category', 'l2_category'])['correct'].mean().reset_index()
results.pivot_table(index=['model_full', 'condition'], columns=[ 'category', 'l2_category'], values=['correct'])

                                                        correct  \
category                                      coarse perception
l2_category                                       image emotion
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind          0.193548
OpenGVLab/InternVL3_5-4B                               0.000000
                                  _inst_blind          0.258065
OpenGVLab/InternVL3_5-8B                               0.774194
                                  _inst_blind          0.451613
Qwen/Qwen3-VL-4B-Instruct                              0.161290
                                  _inst_blind          0.322581
Qwen/Qwen3-VL-8B-Instruct                              0.483871
                                  _inst_blind          0.161290
llava-hf/llava-v1.6-mistral-7b-hf                      0.580645
                                  _inst_blind          0.032258

                                                                     \
category
l2_category                                   image scene and topic
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind              0.042553
OpenGVLab/InternVL3_5-4B                                   0.047619
                                  _inst_blind              0.063830
OpenGVLab/InternVL3_5-8B                                   0.588652
                                  _inst_blind              0.283688
Qwen/Qwen3-VL-4B-Instruct                                  0.411348
                                  _inst_blind              0.148936
Qwen/Qwen3-VL-8B-Instruct                                  0.425532
                                  _inst_blind              0.198582
llava-hf/llava-v1.6-mistral-7b-hf                          0.453901
                                  _inst_blind              0.212766

                                                                     \
category
l2_category                                   image style & quality
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind              0.038462
OpenGVLab/InternVL3_5-4B                                   0.333333
                                  _inst_blind              0.000000
OpenGVLab/InternVL3_5-8B                                   0.769231
                                  _inst_blind              0.333333
Qwen/Qwen3-VL-4B-Instruct                                  0.397436
                                  _inst_blind              0.153846
Qwen/Qwen3-VL-8B-Instruct                                  0.666667
                                  _inst_blind              0.141026
llava-hf/llava-v1.6-mistral-7b-hf                          0.628205
                                  _inst_blind              0.089744

                                                                       \
category                                      fine-grained perception
l2_category                                              localization
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind                   0.000
OpenGVLab/InternVL3_5-4B                                          NaN
                                  _inst_blind                   0.100
OpenGVLab/InternVL3_5-8B                                        0.675
                                  _inst_blind                   0.250
Qwen/Qwen3-VL-4B-Instruct                                       0.325
                                  _inst_blind                   0.150
Qwen/Qwen3-VL-8B-Instruct                                       0.550
                                  _inst_blind                   0.250
llava-hf/llava-v1.6-mistral-7b-hf                               0.400
                                  _inst_blind                   0.100

                                                                           \
category
l2_category                                   object counting recognition
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind        0.000000    0.050847
OpenGVLab/InternVL3_5-4B                                  NaN         NaN
                                  _inst_blind        0.032609    0.059322
OpenGVLab/InternVL3_5-8B                             0.456522    0.491525
                                  _inst_blind        0.206522    0.228814
Qwen/Qwen3-VL-4B-Instruct                            0.130435    0.220339
                                  _inst_blind        0.152174    0.228814
Qwen/Qwen3-VL-8B-Instruct                            0.206522    0.322034
                                  _inst_blind        0.086957    0.093220
llava-hf/llava-v1.6-mistral-7b-hf                    0.239130    0.398305
                                  _inst_blind        0.086957    0.211864

                                                                                  \
category                                                      instance reasoning
l2_category                                   cross-instance attribute reasoning
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind                           0.044944
OpenGVLab/InternVL3_5-4B                                                     NaN
                                  _inst_blind                           0.179775
OpenGVLab/InternVL3_5-8B                                                0.300000
                                  _inst_blind                           0.269663
Qwen/Qwen3-VL-4B-Instruct                                               0.449438
                                  _inst_blind                           0.202247
Qwen/Qwen3-VL-8B-Instruct                                               0.483146
                                  _inst_blind                           0.235955
llava-hf/llava-v1.6-mistral-7b-hf                                       0.348315
                                  _inst_blind                           0.123596

                                                                                 \
category
l2_category                                   cross-instance relation reasoning
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind                          0.016129
OpenGVLab/InternVL3_5-4B                                                    NaN
                                  _inst_blind                          0.016129
OpenGVLab/InternVL3_5-8B                                               0.142857
                                  _inst_blind                          0.274194
Qwen/Qwen3-VL-4B-Instruct                                              0.516129
                                  _inst_blind                          0.145161
Qwen/Qwen3-VL-8B-Instruct                                              0.516129
                                  _inst_blind                          0.129032
llava-hf/llava-v1.6-mistral-7b-hf                                      0.306452
                                  _inst_blind                          0.048387

                                                                         \
category
l2_category                                   single-instance reasoning
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind                  0.020202
OpenGVLab/InternVL3_5-4B                                            NaN
                                  _inst_blind                  0.030303
OpenGVLab/InternVL3_5-8B                                       0.277778
                                  _inst_blind                  0.191919
Qwen/Qwen3-VL-4B-Instruct                                      0.414141
                                  _inst_blind                  0.080808
Qwen/Qwen3-VL-8B-Instruct                                      0.444444
                                  _inst_blind                  0.101010
llava-hf/llava-v1.6-mistral-7b-hf                              0.505051
                                  _inst_blind                  0.101010

                                                                         \
category                                              logical reasoning
l2_category                                   code & sequence reasoning
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind                  0.000000
OpenGVLab/InternVL3_5-4B                                            NaN
                                  _inst_blind                  0.000000
OpenGVLab/InternVL3_5-8B                                            NaN
                                  _inst_blind                  0.051282
Qwen/Qwen3-VL-4B-Instruct                                      0.282051
                                  _inst_blind                  0.128205
Qwen/Qwen3-VL-8B-Instruct                                      0.256410
                                  _inst_blind                  0.102564
llava-hf/llava-v1.6-mistral-7b-hf                              0.025641
                                  _inst_blind                  0.000000

                                                                \
category
l2_category                                   common reasoning
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind         0.049505
OpenGVLab/InternVL3_5-4B                                   NaN
                                  _inst_blind         0.074074
OpenGVLab/InternVL3_5-8B                                   NaN
                                  _inst_blind         0.257426
Qwen/Qwen3-VL-4B-Instruct                             0.376238
                                  _inst_blind         0.198020
Qwen/Qwen3-VL-8B-Instruct                             0.316832
                                  _inst_blind         0.138614
llava-hf/llava-v1.6-mistral-7b-hf                     0.326733
                                  _inst_blind         0.079208

                                                                           \
category                                                             math
l2_category                                   diagram reasoning  geometry
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind          0.018182  0.000000
OpenGVLab/InternVL3_5-4B                                    NaN       NaN
                                  _inst_blind          0.011905       NaN
OpenGVLab/InternVL3_5-8B                                    NaN       NaN
                                  _inst_blind          0.172727  0.025000
Qwen/Qwen3-VL-4B-Instruct                              0.327273  0.155172
                                  _inst_blind          0.109091  0.077586
Qwen/Qwen3-VL-8B-Instruct                              0.272727  0.137931
                                  _inst_blind          0.100000  0.060345
llava-hf/llava-v1.6-mistral-7b-hf                      0.081818  0.000000
                                  _inst_blind          0.036364  0.008621

                                                                                   \
category
l2_category                                   numeric commonsense and calculation
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind                            0.000000
OpenGVLab/InternVL3_5-4B                                                      NaN
                                  _inst_blind                                 NaN
OpenGVLab/InternVL3_5-8B                                                      NaN
                                  _inst_blind                            0.111111
Qwen/Qwen3-VL-4B-Instruct                                                0.291667
                                  _inst_blind                            0.187500
Qwen/Qwen3-VL-8B-Instruct                                                0.187500
                                  _inst_blind                            0.104167
llava-hf/llava-v1.6-mistral-7b-hf                                        0.062500
                                  _inst_blind                            0.000000

                                                                     \
category
l2_category                                   statistical reasoning
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind              0.000000
OpenGVLab/InternVL3_5-4B                                        NaN
                                  _inst_blind                   NaN
OpenGVLab/InternVL3_5-8B                                        NaN
                                  _inst_blind              0.000000
Qwen/Qwen3-VL-4B-Instruct                                  0.197674
                                  _inst_blind              0.058140
Qwen/Qwen3-VL-8B-Instruct                                  0.116279
                                  _inst_blind              0.034884
llava-hf/llava-v1.6-mistral-7b-hf                          0.000000
                                  _inst_blind              0.000000

                                                                             \
category                                               science & technology
l2_category                                   biology & chemistry & physics
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind                           NaN
OpenGVLab/InternVL3_5-4B                                                NaN
                                  _inst_blind                           NaN
OpenGVLab/InternVL3_5-8B                                                NaN
                                  _inst_blind                           NaN
Qwen/Qwen3-VL-4B-Instruct                                          0.287671
                                  _inst_blind                      0.034247
Qwen/Qwen3-VL-8B-Instruct                                          0.321918
                                  _inst_blind                      0.171233
llava-hf/llava-v1.6-mistral-7b-hf                                  0.068493
                                  _inst_blind                      0.020548

                                                                                      \
category
l2_category                                   electronics & energy & mechanical eng.
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind                                    NaN
OpenGVLab/InternVL3_5-4B                                                         NaN
                                  _inst_blind                                    NaN
OpenGVLab/InternVL3_5-8B                                                         NaN
                                  _inst_blind                                    NaN
Qwen/Qwen3-VL-4B-Instruct                                                   0.173913
                                  _inst_blind                               0.000000
Qwen/Qwen3-VL-8B-Instruct                                                   0.260870
                                  _inst_blind                               0.108696
llava-hf/llava-v1.6-mistral-7b-hf                                           0.043478
                                  _inst_blind                               0.000000


category
l2_category                                   geography & earth science & agriculture
model_full                        condition
OpenGVLab/InternVL3_5-2B          _inst_blind                                     NaN
OpenGVLab/InternVL3_5-4B                                                          NaN
                                  _inst_blind                                     NaN
OpenGVLab/InternVL3_5-8B                                                          NaN
                                  _inst_blind                                     NaN
Qwen/Qwen3-VL-4B-Instruct                                                    0.379310
                                  _inst_blind                                0.155172
Qwen/Qwen3-VL-8B-Instruct                                                    0.327586
                                  _inst_blind                                0.155172
llava-hf/llava-v1.6-mistral-7b-hf                                            0.086207
                                  _inst_blind                                0.051724